services:
  saas_postgres:
    image: postgres:16-alpine
    container_name: saas_postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=saas_omnichannel
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  saas_redis:
    image: redis:7-alpine
    container_name: saas_redis
    ports:
      - "6379:6379"
    restart: always

  saas_rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: saas_rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password123
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

  saas_mongo:
    image: mongo:7
    container_name: saas_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  saas_api:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: saas_api
    depends_on:
      - saas_postgres
      - saas_redis
      - saas_rabbitmq
      - saas_mongo
      - saas_whatsapp_bridge
    environment:
      - DOCKER_CONTAINER=true
      - POSTGRES_SERVER=saas_postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=saas_omnichannel
      - MONGODB_URL=mongodb://saas_mongo:27017/SaaS_Chatbot
      - REDIS_URL=redis://saas_redis:6379/0
      - RABBITMQ_URL=amqp://admin:password123@saas_rabbitmq/
      - WHATSAPP_BRIDGE_URL=http://saas_whatsapp_bridge:4000
    ports:
      - "8001:8000"
    volumes:
      - ./uploads:/app/uploads
    restart: always

  saas_whatsapp_bridge:
    build:
      context: ./SaaS.OmniChannelPlatform.Services.WhatsAppBot
    container_name: saas_whatsapp_bridge
    environment:
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable
    shm_size: '2gb'
    ports:
      - "4000:4000"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - ./SaaS.OmniChannelPlatform.Services.WhatsAppBot/tokens:/app/tokens
    restart: always

volumes:
  postgres_data:
  mongo_data:
